use int_ques;


--LIST ALL THE AVAILABLE DATABASE 

SP_DATABASES
SELECT * FROM SYS.DATABASES
SELECT * FROM SYS.MASTER_FILES  

--LIST USER TABLES IN THE DATABASE

SELECT * FROM SYS.OBJECTS WHERE type = 'U'
SELECT * FROM SYSOBJECTS WHERE xtype = 'U'
SELECT * FROM SYS.TABLES 
SELECT * FROM SYS.ALL_OBJECTS WHERE type = 'U'
SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'
SP_TABLES


--LIST STORED PROCEDURES IN A DATABASE
SELECT * FROM SYS.OBJECTS WHERE type = 'P'
SELECT * FROM SYS.PROCEDURES 
SELECT * FROM SYS.ALL_OBJECTS WHERE type = 'P'
SELECT * FROM SYSOBJECTS WHERE xtype='P'
SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE'

--SUMMARY
SYS.OBJECTS (table-procedure-view-functions-triggers-checkconstraint)
SYS.ALL_OBJECTS (table-procedure-view-functions)
INFORMATION_SCHEMA.TABLES/ROUTINES(procedure-functions)/VIEWS/COLUMNS
SYS.TABLES/PROCEDURES/VIEWS/DATABASES/TRIGGERS/COLUMNS/check_constraints/INDEXES

SELECT * FROM SYS.OBJECTS
SELECT * FROM SYS.ALL_OBJECTS
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
SELECT * FROM SYS.all_views

--IN-BUILT STORED PROCEDURES
SP_HELP accreditations
SP_COLUMNS accreditations

--INDEX
SP_HELPINDEX ACCREDITATIONS

